name = "Andromeda Light"
license = "MIT"
licenselink = "https://github.com/gethugothemes/andromeda-light/blob/master/LICENSE"
description = "Andromeda is a SAAS landing template focused on real life usages and clean interface. It is fully responsive, Super fast and powered by Bootstrap. You can buy premium version from [gethugothemes](https://gethugothemes.com/products/andromeda/) for full access of this amazing template."
homepage = "https://github.com/gethugothemes/andromeda-light/"
demosite = "https://demo.gethugothemes.com/andromeda-light/"
tags = ['blog', 'light', 'bootstrap', "company", 'responsive', 'contact-form']
features = ['responsive']
min_version = "0.83.1"

[author]
name = "gethugothemes"
homepage = "https://gethugothemes.com/"